server:
  port: 2001

spring:
  application:
    name: cloud-config-server #注册到eureka服务的微服务名
  cloud:
    config:
      server:
        git:
          # github上面git仓库的名字
          uri: https://github.com/MouGuangJun/springcloud-config.git
          # uri: git@github.com:MouGuangJun/springcloud-config.git
          # 搜索目录
          search-paths:
            - spring-cloud-config
          #username: MouGuangJun
          #password: GIT@MOUGUANGJUN.COM
      # 读取分支
      label: master

eureka:
  client:
    #表示是否将自己注册进EurekaServer
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机版
      defaultZone: http://localhost:7001/eureka
      #集群版
      # defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
